We need to decrypt the key file first

diff --git a/webmux_client b/webmux_client
--- a/webmux_client
+++ b/webmux_client
@@ -14,6 +14,10 @@ if [[ -z "$WEBMUX_PORT" ]]; then
 fi
 if [[ -z "$WEBMUX_SSH_KEY_FILE" ]]; then
     WEBMUX_SSH_KEY_FILE="$HOME/etc/secure/ssh/external/webmux_rsa"
+    if [[ ! decrypted ${WEBMUX_SSH_KEY_FILE} ]]; then
+        echo "ERROR: Must decrypt webmux key!"
+        exit 1
+    fi
 fi
 chmod 0600 "$WEBMUX_SSH_KEY_FILE"
 
